install.packages(c("ggplot2", "ggpubr", "tidyverse", "broom", "AICcmodavg"))
library(ggplot2)
library(ggpubr)
library(tidyverse)
library(broom)
library(AICcmodavg)
crop.data <- read.csv("C:/Users/dines/OneDrive/Documents", header = TRUE, colClasses = 
                        c("factor", "factor", "factor", "numeric"))
summary(crop.data)
one.way <- aov(yield ~ fertilizer, data = crop.data)
summary(one.way)
two.way <- aov(yield ~ fertilizer + density, data = crop.data)
summary(two.way)
interaction <- aov(yield ~ fertilizer*density, data = crop.data)
summary(interaction)
plot(one.way)
plot(two.way)